### PR TITLE
update runtime to 21.08

### LINKED ISSUE #1: update freedesktop runtime to 20.08

### LINKED ISSUE #2: Just comes up with a black window
I would love to use this to stress test and benchmark my computer, but when I open it, all that appears is a black window.

```
Aura ~ $ dgpu flatpak run com.basemark.BasemarkGPU 
hostname: invalid option -- 'f'
Try 'hostname --help' for more information.
Gtk-Message: 22:15:39.594: Failed to load module "canberra-gtk-module"
(node:3) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(Use `basemarkgpu --trace-warnings ...` to show where the warning was created)
```

If I run the regular tarball from their website, something similar happens, except that the window is transparent and unresponsive.

### PR DESCRIPTION
**Pull request by sonnyp**
Fixes #1
Fixes #2

### CODE REVIEW

**Comment by hfiguiere** [comment]
the README should be updated too.

**Comment by sonnyp** [comment]
done

I took some liberty in updating the README.md, feel free to edit

**Comment by sonnyp** [comment]
bot, build

**Comment by sonnyp** [comment]
Could a flathub maintainer/administrator have a look at why the build is constantly failing with `No space left on device` ?

**Comment by bilelmoussaoui** [comment]
> Could a flathub maintainer/administrator have a look at why the build is constantly failing with `No space left on device` ?

It was an issue on the sources machine, it should be fixed now

**Comment by sonnyp** [comment]
bot, build

**Comment by sonnyp** [comment]
ping @JuhoBasemark

**Comment by hfiguiere** [comment]
Maybe moving to 21.08 is appropriate now?

**Comment by sonnyp** [comment]
Done - please consider merging - BasemarkGPU is broken right now on flathub. I can revert the changes to the README if that's blocking.

**Comment by sonnyp** [comment]
ping

**Pull request merged**
